version: '3'
services:
  web:
    build:
      context: .
      target: build_as_root
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: db
      BUCKET_NAME: bright_storage_local
      GCS_BASE_URL: http://gcs:4443
      # NOTE: SNS ログインをローカルでデバッグしたいときは以下を記載
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
    links:
      - db
      - gcs
    ports:
      - 4000:4000
    volumes:
      - .:/work
    working_dir: /work
    command: "elixir --sname bright@web --cookie bright -S mix phx.server"
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  livebook:
    image: ghcr.io/livebook-dev/livebook
    environment:
      - LIVEBOOK_COOKIE=bright
      - LIVEBOOK_DEFAULT_RUNTIME=attached:bright@web:bright
      - LIVEBOOK_TOKEN_ENABLED=false
      - LIVEBOOK_HOME=/data
    links:
      - web
    ports:
      - 8080:8080
    volumes:
      - ./livebook:/data
  gcs:
    image: ghcr.io/s12m/fake-gcs-server:1.45.2
    ports:
      - 4443:4443
    volumes:
      - gcsdata:/storage/bright_storage_local
volumes:
  dbdata:
  gcsdata:
