Bright.Seeds.Job.delete()
Bright.Seeds.CareerField.delete()
Bright.Seeds.SkillPanel.delete()
Bright.Seeds.CareerWants.delete()
Bright.Seeds.CareerField.insert()
Bright.Seeds.SkillPanel.insert()
Bright.Seeds.Job.insert()
Bright.Seeds.CareerWants.insert()
