name: CI for development

# 起動タイミングは以下
# 1. PR が open もしくは reopen した時、またはコミットなどにより head が更新された時
# 2. main ブランチに push された時 (= main ブランチにマージされた時)
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "docker_dev/**"
      - "livebook/**"
      - "Makefile"
      - ".dockerignore"
      - ".editorconfig"
      - ".gitignore"
      - "README.md"
  push:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "docker_dev/**"
      - "livebook/**"
      - "Makefile"
      - ".dockerignore"
      - ".editorconfig"
      - ".gitignore"
      - "README.md"

jobs:
  test:
    name: Build & Test & FormatCheck & Credo
    runs-on: ubuntu-latest

    defaults:
      run:
        # working-directory: checkoutする場所かつ、stepsのデフォルト作業位置
        # servicesのマウントで使用する場所(github.workspace)とずらすために設定している
        # refs: https://su-kun1899.hatenablog.com/entry/2023/01/25/090000
        working-directory: srv

    container:
      image: hexpm/elixir:1.14.5-erlang-26.0-debian-bullseye-20230227-slim
      env:
        MIX_ENV: test
        GCS_BASE_URL: https://gcs:4443

    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      gcs:
        image: fsouza/fake-gcs-server:1.45.2
        ports:
          - 4443:4443
        # 起動オプションを設定するために独自チェックポイントを指定
        volumes:
          - ${{github.workspace}}/.github/workflows/gcs:/usr/bin/gcs
        options: --entrypoint "/usr/bin/gcs/checkpoint.sh"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: srv

      - name: Copy fake gcs checkpoint
        run: |
          cp -r .github/workflows/gcs ${{github.workspace}}/.github/workflows/gcs

      - name: Cache deps and _build
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Dependencies install
        run: |
          apt-get update -y && apt-get install -y build-essential inotify-tools git

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Test
        run: |
          mix deps.compile
          mix compile --warnings-as-errors
          mix test --warnings-as-errors
        env:
          DB_HOST: postgres
          DB_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Format Checks
        run: |
          mix format --check-formatted

      - name: Credo Checks
        run: |
          mix credo
