name: Reusable deploy

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        type: string
        required: true
      service_account:
        type: string
        required: true
      image_name:
        type: string
        required: true
      cloud_sql_instance:
        type: string
        required: true
      cloud_run_service_account:
        type: string
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
      - uses: google-github-actions/setup-gcloud@v1
      - name: Cloud Build submit
        run: |
          gcloud builds submit \
            --substitutions=_IMAGE_NAME=$IMAGE_NAME,_CLOUD_SQL_INSTANCE=$CLOUD_SQL_INSTANCE,_SERVICE_ACCOUNT=$SERVICE_ACCOUNT \
            --async
        env:
          IMAGE_NAME: ${{ inputs.image_name }}
          CLOUD_SQL_INSTANCE: ${{ inputs.cloud_sql_instance }}
          SERVICE_ACCOUNT: ${{ inputs.cloud_run_service_account }}
